pipeline{
    agent any

    stages {('Initial Setup')
        steps{
            dir("$WORKSPACE"){
                deleteDir()
            }
        }
        
    }
}

// pipeline {
//     agent any

//     stages {
//       //Setup stage to delete the workspace, that is cleanup the workspace on the jenkins server
//         stage('Ininitial Cleanup'){
//             steps{
//                 dir("$WORKSPACE"){
//                   deleteDir()
//                 }
//             }
//             }
//         stage('Build') {
//             steps {
//                 script {
//                     sh 'echo "Building Stage"'
//                 }
//             }
//         }

//         stage('Test') {
//             steps {
//                 script {
//                     sh 'echo "Testing Stage"'
//                 }
//             }
//         }

//         stage('Package') {
//             steps {
//                 script {
//                     sh 'echo "Package Stage"'
//                 }
//             }
//         }

//         stage('Deploy') {
//             steps {
//                 script {
//                     sh 'echo "Deploy Stage"'
//                 }
//             }
//         }

//         //  Setup stage to delete the workspace, that is cleanup the workspace on the jenkins server
//         stage('Clean up') {
//             steps {
//                 script {
//                     sh 'echo "Clean up"'
//                 }
//                 cleanWs()
//             }
//         }
//     }

//     post {
//         success {
//             echo 'All stages executed successfully!'
//         }
//         failure {
//             echo 'Pipeline failed. Check logs for details.'
//         }
//     }
// }
